name: Jewel Apothecary
favicon: null
layout_spectrum: 0.10176991601474583
typography_spectrum: 0.988382495008409
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.38962981989607215
  lightness: 0.08301727846264839
  saturation: 0.7380611856933683
  rhythmicContrast: 0.10703221638686955
purpose: []
